<?xml version="1.0"?>
<?xml-model href="http://ros.org" schematypens="http://w3.org"?>
<package format="3">
  <name>led_control_msgs</name>
  <version>0.0.1</version>
  <description>Custom LED messages for ESP32</description>
  <maintainer email="nickmanda@gmail.com">Nick</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
